# This file generates the GitHub Actions matrix
---
include:
  - board: nice_nano_k/nrf52833
    shield: velvet_nano_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=256 -DCONFIG_ZMK_DISPLAY=n -DCONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n -DCONFIG_LV_Z_MEM_POOL_SIZE=0 -DCONFIG_ZMK_BACKLIGHT=n -DCONFIG_LVGL=n -DCONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=6000 -DCONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=16 -DCONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=256 -DCONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=256 -DCONFIG_ZMK_STUDIO_RPC_CUSTOM_SUBSYSTEM_REQUEST_PAYLOAD_MAX_BYTES=256 -DCONFIG_ZMK_CUSTOM_SETTINGS_LARGE_VALUE_MAX_SIZE=256 -DCONFIG_BT_BUF_ACL_TX_COUNT=3 -DCONFIG_BT_BUF_EVT_RX_COUNT=6 -DCONFIG_BT_L2CAP_TX_BUF_COUNT=4
    artifact: velvet_nano_dongle
  - board: nice_nano//zmk
    shield: velvet_left nice_view_custom velvet_split_peripheral
    cmake-args: -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y -DCONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=256
    artifact: velvet_left_dongle
  - board: nice_nano//zmk
    shield: velvet_right nice_view velvet_split_peripheral
    cmake-args: -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y -DCONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=256
    artifact: velvet_right_dongle
  - board: nice_nano_k/nrf52833
    shield: settings_reset
    artifact: settings_reset_nano
  - board: nice_nano//zmk
    shield: settings_reset
    artifact: settings_reset
