manifest:
  version: 1.2
  defaults:
    remote: cormoran
    revision: main
  remotes:
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: a741725193
      url-base: https://github.com/a741725193
  projects:
    - name: zmk-west-commands
      remote: cormoran
      revision: v1.0.0
      import: true
    - name: zmk
      remote: cormoran
      revision: main+dya
      import: app/west.yml
      clone-depth: 1
    - name: zephyr
      remote: cormoran
      revision: v4.1.0+zmk-fixes+nrf-half-duplex-uart
      clone-depth: 1
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_xtensa
          - hal_st
          - hal_ti
          - loramac-node
          - mcuboot
          - mcumgr
          - net-tools
          - openthread
          - edtt
          - trusted-firmware-m
          - chre
    - name: zmk-module-ble-management
      import: true
    - name: zmk-module-battery-history
    - name: zmk-module-settings-rpc
      import: true
    - name: zmk-feature-custom-settings
      import: true
    - name: zmk-feature-fast-keymap
      import: true
    - name: zmk-feature-device-info
      import: true
    - name: zmk-feature-watchdog
    - name: zmk-feature-input-stream
      import: true
    - name: zmk-feature-module-physical-layout
      import: true
    - name: zmk-feature-default-layer
      import: true
      revision: codex/custom-rpc-rewrite
    - name: zmk-feature-os-detection
      import: true
    - name: zmk-feature-runtime-macro
      import: true
    - name: zmk-feature-runtime-combo
      import: true
    - name: zmk-feature-kscan-diagnostics
    - name: zmk-tog-io
      remote: a741725193
      revision: main
    - name: mario-peripheral-animation
      remote: gpeye
      revision: main
  self:
    path: config
