# The Prospector dongle is the split central; the keyboard halves are peripherals by default.
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
CONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=240
